version: '2'

services:

    mongo-express:
        image: autopilotpattern/mongo-express
        build: .
        restart: always
        mem_limit: 512m
        env_file: _env
        environment:
            - ME_CONFIG_OPTIONS_EDITORTHEME=ambiance
# ME_CONFIG_MONGODB_SERVER will get re-written by consul-template
            - ME_CONFIG_MONGODB_SERVER=mongodb
        ports:
            - 8081

    mongodb:
        image: autopilotpattern/mongodb
        command: containerpilot mongod --replSet=pilot
        restart: always
        mem_limit: 512m
        env_file: _env
        ports:
            - 27017

    consul:
        image: consul:0.7.2
        command: agent -dev -ui -client=0.0.0.0
        restart: always
        mem_limit: 128m
        ports:
            - 8500
        expose:
            - 53
            - 8300
            - 8301
            - 8302
            - 8400
            - 8500
